apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: <ECR_FRONTEND_IMAGE>
          env:
            - name: REACT_APP_MOVIE_API_URL
              value: "http://<backend-service-url>/movies"
          ports:
            - containerPort: 80
