name: Backend CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd backend && npm install && npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd backend && npm install && npm test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t backend-app ./backend

  push-to-ecr:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/amazon-ecr-login@v1
      - run: |
          docker tag backend-app:latest ${{ secrets.ECR_REGISTRY }}/backend-app:latest
          docker push ${{ secrets.ECR_REGISTRY }}/backend-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: push-to-ecr
    steps:
      - uses: actions/checkout@v3
      - run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER }}
          kubectl apply -f ./k8s/backend-deployment.yaml
