name: Frontend CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  IMAGE_TAG: latest
  ECR_REPOSITORY: 949829287785.dkr.ecr.us-east-1.amazonaws.com/udacity-frontend-repo

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./movie-app/frontend
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./movie-app/frontend
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: Run tests
        run: npm test

  build-and-push:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        working-directory: ./movie-app/frontend
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=${{ secrets.REACT_APP_MOVIE_API_URL }} \
            -t $ECR_REPOSITORY:$IMAGE_TAG \
            .

      
      - name: Push Docker image
        run: docker push $ECR_REPOSITORY:$IMAGE_TAG

