name: Frontend CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=${{ secrets.REACT_APP_MOVIE_API_URL }} \
            -t frontend-app ./frontend

  push-to-ecr:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/amazon-ecr-login@v1
      - run: |
          docker tag frontend-app:latest ${{ secrets.ECR_REGISTRY }}/frontend-app:latest
          docker push ${{ secrets.ECR_REGISTRY }}/frontend-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: push-to-ecr
    steps:
      - uses: actions/checkout@v3
      - run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER }}
          kubectl apply -f ./k8s/frontend-deployment.yaml
