name: Frontend CD

on:
  push:
    branches: [ main ]
    paths:
      - 'movie-app/frontend/**'

jobs:
  frontend-cd:
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: movie-app/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        env:
          ECR_REPOSITORY: udacity-frontend-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGION=${{ secrets.AWS_REGION }}
          IMAGE_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"

          BACKEND_API_URL="http://aa45ec4cc8ff945dab5f3213a6f5449a-1309775917.us-east-1.elb.amazonaws.com"

          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=$BACKEND_API_URL \
            -t $IMAGE_URI .
          docker push $IMAGE_URI

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        env:
          IMAGE_URI: 949829287785.dkr.ecr.us-east-1.amazonaws.com/udacity-frontend-repo:${{ github.sha }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sed -i "s|__IMAGE_TAG__|${{ github.sha }}|" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
