name: Test Frontend CI

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Show folders
        run: |
          pwd
          ls -la
          ls -la movie-app
          ls -la movie-app/frontend

      - name: Install dependencies
        working-directory: movie-app/frontend
        run: npm install
        
      - name: Run linter
        working-directory: movie-app/frontend
        run: npm run lint

