apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 949829287785.dkr.ecr.us-east-1.amazonaws.com/udacity-backend-repo:latest
        ports:
        - containerPort: 3001
