apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 949829287785.dkr.ecr.us-east-1.amazonaws.com/udacity-backend-repo:__IMAGE_TAG__
        ports:
        - containerPort: 3001
        - name: backend
          image: 949829287785.dkr.ecr.us-east-1.amazonaws.com/udacity-backend-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
